name: app_pasajero_ns
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animate_do: ^3.0.0
  auto_animated: ^3.0.0
  clippy_flutter: ^2.0.0-nullsafety.1
  cloud_firestore: ^4.11.0
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  dotted_border: ^2.0.0+1
  file: ^7.0.0
  firebase_auth: ^4.6.1
  firebase_core: ^2.18.0
  firebase_messaging: ^14.7.1
  firebase_storage: ^11.3.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.2
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.0.0
  freezed_annotation: ^0.14.1
  geocoding: ^2.1.1
  geoflutterfire2: ^2.3.15
  geolocator: ^10.1.0
  get: ^4.6.1
  get_storage: ^2.1.1
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.1.5
  grouped_list: ^4.0.0
  image_picker: ^1.0.4
  internet_connection_checker: ^0.0.1+2
  intl: ^0.18.0
  keyboard_actions: ^4.2.0
  location: ^5.0.3
  logger: ^1.0.0
  lottie: ^1.0.1
  maps_curved_line: ^1.0.2
  mask_text_input_formatter: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre
  permission_handler: ^11.0.1
  photo_view: ^0.14.0
  pin_code_fields: ^8.0.1
  share_plus: ^7.2.2
  skeleton_text: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  sms_autofill: ^2.2.0
  url_launcher: ^6.0.6
  uuid: ^3.0.4
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/flags/
    - assets/icons/
    - assets/img/
    - assets/lottie/
    - assets/places/
    - assets/places2/
    - assets/places3/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 200
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
